### ISSUE TITLE
Problem with python 3.10 [Fedora 35]

### ISSUE THREAD

**Issue by samuraee** [shadowsocksrr/shadowsocksr#102]
I get this error after upgrading Python 3.9 to 3.10:

```
Traceback (most recent call last):
  File "/opt/shadowsocksr/shadowsocks/local.py", line 31, in <module>
    from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, asyncdns
  File "/opt/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 26, in <module>
    from shadowsocks.common import to_bytes, to_str, IPNetwork, PortRange
  File "/opt/shadowsocksr/shadowsocks/../shadowsocks/common.py", line 27, in <module>
    from shadowsocks import lru_cache
  File "/opt/shadowsocksr/shadowsocks/../shadowsocks/lru_cache.py", line 44, in <module>
    class LRUCache(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

```
